### ISSUE TITLE
Add a setting to charge to only 80%, then stop charging

### ISSUE THREAD

**Issue by DeflateAwning** [FrameworkComputer/framework-system#5]
I think this is the correct tool to add this sort of charge restriction. I would love a setting where you can make the computer stop charging after reaching an 80% state-of-charge to prolong the battery lifetime

**Comment by JohnAZoidberg** [comment]
Here you go #9  :)

**Comment by DeflateAwning** [comment]
That's insane, thank you!! I love open source. 

Let's hope they review and merge this, as it's a hugely useful feature. Thanks again!

**Comment by JohnAZoidberg** [comment]
> Edit: Just realized that you are Framework. Very, very awesome!

Haha, I am indeed *part of* Framework.

> That's insane, thank you!! I love open source.
We too! We have had contributions to our other repos from a couple of people and I hope to get this project here more useful, too. And hopefully more people can use and improve it.

Maybe you can see how simple my PR was and try the next one yourself ;)

**Comment by DeflateAwning** [comment]
Tested and confirmed that this works! Thanks again!
